### ISSUE TITLE
Modify RETURN TYPE on some functions

### ISSUE THREAD

**Issue by ghost** [atul19971/crypto4ora#4]
Considering RSA's specs permit keys up to 4096 it is required to change from VARCHAR2 to CLOB the RETURN TYPE of the following functions:

`RSA_ENCRYPT
RSA_DECRYPT
RSA_GENERATE_KEYS`

This is because VARCHAR2 cannot hold more than 4000 bytes.

**Comment by atul19971** [comment]
From 12c varchar2 is having maxlength 32767.
But we will try to resolve this in next version so that we can support older version too.

**Comment by antonscheffer** [comment]
No need to extend that to clob. Key size is in bits, not bytes. A key of 16384 bits can easily be stored in a varchar2(4000), even when it is base64 encoded.
